# Generated by Django 4.1.7 on 2023-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('birthplace', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=80)),
                ('father_name', models.CharField(max_length=80)),
                ('registrar_done', models.BooleanField()),
                ('clearance_done', models.BooleanField()),
                ('pta_done', models.BooleanField()),
                ('enrolled_subjects', models.CharField(max_length=800)),
                ('year_level', models.CharField(choices=[('IU-Y1', '1st Year'), ('IU-Y2', '2nd Year'), ('IU-Y3', '3rd Year'), ('IU-Y4', '4th Year')], max_length=20)),
            ],
        ),
    ]
