# Generated by Django 4.2 on 2023-04-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_current_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_subjects',
        ),
    ]
