# Generated by Django 4.2 on 2023-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_enrolled_subjects'),
        ('subjects', '0004_remove_subject_enrolled_count_subjectstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(through='subjects.SubjectStudent', to='subjects.subject'),
        ),
    ]
