# Generated by Django 4.2 on 2023-04-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_professor'),
        ('students', '0006_student_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(related_name='Schedule_subject', through='schedules.StudentSchedule', to='schedules.schedule'),
        ),
    ]
