# Generated by Django 4.2 on 2023-04-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schedules',
        ),
    ]
