# Generated by Django 4.2 on 2023-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
    ]
