# Generated by Django 4.2 on 2023-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_professor'),
        ('students', '0010_alter_student_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(related_name='StudentSchedule_subject', through='schedules.StudentSchedule', to='schedules.schedule'),
        ),
    ]
