# Generated by Django 4.2 on 2023-04-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_schedule_semester'),
        ('students', '0011_student_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(null=True, related_name='StudentSchedule_subject', through='schedules.StudentSchedule', to='schedules.schedule'),
        ),
    ]
