# Generated by Django 4.2 on 2023-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='full_name',
            field=models.CharField(db_column='full_name', default=' ', max_length=80),
            preserve_default=False,
        ),
    ]
