# Generated by Django 4.2 on 2023-04-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professor_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='full_name',
        ),
    ]
