# Generated by Django 4.2 on 2023-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_remove_professor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='full_name',
            field=models.CharField(default=' ', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
