# Generated by Django 4.2 on 2023-04-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_code_alter_subject_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
