# Generated by Django 4.2 on 2023-04-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_delete_subjectstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='max_slots',
        ),
    ]
