# Generated by Django 4.2 on 2023-04-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Professor_full_name', to='professors.professor'),
        ),
    ]
