# Generated by Django 4.2 on 2023-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.TextField(default='PlaceholderName'),
            preserve_default=False,
        ),
    ]
