# Generated by Django 4.2 on 2023-04-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daytimes', '0001_initial'),
        ('schedules', '0003_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='daytimes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DayTime_full_name', to='daytimes.daytime'),
        ),
    ]
