# Generated by Django 4.2 on 2023-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_schedule_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.TextField(default='Placeholder Semester'),
            preserve_default=False,
        ),
    ]
